/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CompetitiveRouteImport } from './routes/competitive'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeetingsIndexRouteImport } from './routes/meetings.index'
import { Route as AccountsIndexRouteImport } from './routes/accounts.index'
import { Route as MeetingsIdRouteImport } from './routes/meetings.$id'
import { Route as AccountsIdRouteImport } from './routes/accounts.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitiveRoute = CompetitiveRouteImport.update({
  id: '/competitive',
  path: '/competitive',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsIndexRoute = MeetingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeetingsRoute,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountsRoute,
} as any)
const MeetingsIdRoute = MeetingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MeetingsRoute,
} as any)
const AccountsIdRoute = AccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/ask': typeof AskRoute
  '/competitive': typeof CompetitiveRoute
  '/documents': typeof DocumentsRoute
  '/meetings': typeof MeetingsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/meetings/$id': typeof MeetingsIdRoute
  '/accounts/': typeof AccountsIndexRoute
  '/meetings/': typeof MeetingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/competitive': typeof CompetitiveRoute
  '/documents': typeof DocumentsRoute
  '/settings': typeof SettingsRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/meetings/$id': typeof MeetingsIdRoute
  '/accounts': typeof AccountsIndexRoute
  '/meetings': typeof MeetingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/ask': typeof AskRoute
  '/competitive': typeof CompetitiveRoute
  '/documents': typeof DocumentsRoute
  '/meetings': typeof MeetingsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/meetings/$id': typeof MeetingsIdRoute
  '/accounts/': typeof AccountsIndexRoute
  '/meetings/': typeof MeetingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/ask'
    | '/competitive'
    | '/documents'
    | '/meetings'
    | '/settings'
    | '/accounts/$id'
    | '/meetings/$id'
    | '/accounts/'
    | '/meetings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/competitive'
    | '/documents'
    | '/settings'
    | '/accounts/$id'
    | '/meetings/$id'
    | '/accounts'
    | '/meetings'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/ask'
    | '/competitive'
    | '/documents'
    | '/meetings'
    | '/settings'
    | '/accounts/$id'
    | '/meetings/$id'
    | '/accounts/'
    | '/meetings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRouteWithChildren
  AskRoute: typeof AskRoute
  CompetitiveRoute: typeof CompetitiveRoute
  DocumentsRoute: typeof DocumentsRoute
  MeetingsRoute: typeof MeetingsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitive': {
      id: '/competitive'
      path: '/competitive'
      fullPath: '/competitive'
      preLoaderRoute: typeof CompetitiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/': {
      id: '/meetings/'
      path: '/'
      fullPath: '/meetings/'
      preLoaderRoute: typeof MeetingsIndexRouteImport
      parentRoute: typeof MeetingsRoute
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/meetings/$id': {
      id: '/meetings/$id'
      path: '/$id'
      fullPath: '/meetings/$id'
      preLoaderRoute: typeof MeetingsIdRouteImport
      parentRoute: typeof MeetingsRoute
    }
    '/accounts/$id': {
      id: '/accounts/$id'
      path: '/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AccountsIdRouteImport
      parentRoute: typeof AccountsRoute
    }
  }
}

interface AccountsRouteChildren {
  AccountsIdRoute: typeof AccountsIdRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsIdRoute: AccountsIdRoute,
  AccountsIndexRoute: AccountsIndexRoute,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

interface MeetingsRouteChildren {
  MeetingsIdRoute: typeof MeetingsIdRoute
  MeetingsIndexRoute: typeof MeetingsIndexRoute
}

const MeetingsRouteChildren: MeetingsRouteChildren = {
  MeetingsIdRoute: MeetingsIdRoute,
  MeetingsIndexRoute: MeetingsIndexRoute,
}

const MeetingsRouteWithChildren = MeetingsRoute._addFileChildren(
  MeetingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRouteWithChildren,
  AskRoute: AskRoute,
  CompetitiveRoute: CompetitiveRoute,
  DocumentsRoute: DocumentsRoute,
  MeetingsRoute: MeetingsRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
